packages:
  - "apps/*"
  - "packages/*"
  - "tools"
  - "tests/integration"
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1115.0'
